In [7]:
import numpy as np

a=np.array([1,2,3,4])
print(a.ndim)
print(a.shape)
print(a)

1
(4,)
[1 2 3 4]


In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
print(a.ndim)
print(a.shape)
print(a[1][2])
print(a[0][3])

2
(2, 4)
7
4


In [12]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
print(a.shape)

(1, 2, 4)


In [13]:
a[0][1][2]   #row,dim,col

7

In [15]:
a=np.arange(1,11)
a[7]

8

In [18]:
a=np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [19]:
a[1][3]

10

In [21]:
a=np.arange(1,61).reshape(5,2,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [22]:
a[1][0][3]

16