In [3]:
import numpy as np

a=np.linspace(11,20,4)
print(a)

[11. 14. 17. 20.]


In [7]:
a=np.zeros([3,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
a=np.ones((3,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
a=np.random.randint(10,20)
a

14

In [18]:
a=np.random.rand(3,3)
print(a)

[[0.97061969 0.39607217 0.21985438]
 [0.19238382 0.08653524 0.17146929]
 [0.23513683 0.99917789 0.5200754 ]]


In [20]:
a=np.random.randn(3,3)
print(a)

[[-1.94676478 -0.77268609  0.08979113]
 [-0.55605778 -0.90733511 -1.39428345]
 [-0.48323058  0.59273831  0.39083522]]


In [21]:
a=np.random.random((3,3))
print(a)

[[0.57970762 0.86577637 0.49968842]
 [0.97603211 0.36309614 0.69805883]
 [0.03623288 0.78521744 0.17348635]]


In [23]:
a=np.eye(2,2)
print(a)

array([[1., 0.],
       [0., 1.]])

In [25]:
a=np.eye(2,2,dtype=int)
print(a)

[[1 0]
 [0 1]]


In [29]:
a=np.full((3,3),9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [30]:
a=np.full((3,3),9,dtype=int)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [31]:
a=np.array([[1,2,3,4],[11,12,13,14]])
a

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [32]:
b=a.ravel()
print(b)

[ 1  2  3  4 11 12 13 14]


In [33]:
b.ndim

1

In [36]:
a=np.array([[1,2,5,6],[11,12,13,14]])
print(a)

print(a.shape)

[[ 1  2  5  6]
 [11 12 13 14]]
(2, 4)


In [43]:
b=a.T
print(b)
print(b.shape)

[[ 1 11]
 [ 2 12]
 [ 5 13]
 [ 6 14]]
(4, 2)


In [44]:
b=a.transpose()
print(b)
print(b.shape)

[[ 1 11]
 [ 2 12]
 [ 5 13]
 [ 6 14]]
(4, 2)


In [47]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
b=np.array([[11,12,13,14],[21,22,23,24]])
b

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [53]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [21, 22, 23, 24]])

### v_stack & H_stack

In [57]:
a=np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [58]:
b=np.arange(31,41).reshape(2,5)
print(b)

[[31 32 33 34 35]
 [36 37 38 39 40]]


In [60]:
c=np.vstack(a,b)
ck,

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.sum()